[build]
command = "npm install --prefix client && npm run build --prefix client"
publish = "client/build"

[environment]
NODE_OPTIONS = "--openssl-legacy-provider"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
